@php
    $pages = ['profile' => ['Hồ sơ cá nhân', 'Quản lý thông tin tài khoản của bạn trong cổng biên tập.'], 'security' => ['Bảo mật', 'Quản lý phương thức đăng nhập và bảo vệ tài khoản.'], 'appearance' => ['Giao diện', 'Chế độ sáng, tối hoặc theo hệ thống.']];
    [$title, $description] = $pages[$tab] ?? $pages['profile'];
    $profileRoute = fn (string $page = 'profile'): string => $page === 'profile' ? route('editor.profile.show') : route('editor.profile.show', ['tab' => $page]);
    $inputClass = 'mt-1.5 h-10 w-full rounded-lg border border-outline-variant bg-surface px-3 font-body-md text-body-md text-on-surface focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20';
    $completionFields = [filled($user->name), filled($user->avatar_path)];
    $profileCompletion = (int) round(collect($completionFields)->filter()->count() / count($completionFields) * 100);
@endphp

<x-layouts.editor :title="$title">
    <div class="mx-auto w-full max-w-[1040px]">
        <div class="flex flex-col gap-6 lg:flex-row lg:items-start lg:gap-10">
            <aside class="lg:w-56 lg:shrink-0">
                <nav class="lg:hidden" aria-label="Tài khoản biên tập viên"><div class="-mx-1 flex gap-2 overflow-x-auto px-1 pb-1">@foreach (['profile' => ['Hồ sơ biên tập', 'person'], 'security' => ['Bảo mật', 'lock'], 'appearance' => ['Giao diện', 'palette']] as $key => [$label, $icon])<a href="{{ $profileRoute($key) }}" @class(['inline-flex shrink-0 items-center gap-1.5 rounded-full border px-3.5 py-2 font-label-sm text-label-sm', 'border-primary bg-primary/10 font-semibold text-primary' => $tab === $key, 'border-outline-variant bg-surface text-on-surface-variant' => $tab !== $key])><span class="material-symbols-outlined text-[16px]">{{ $icon }}</span>{{ $label }}</a>@endforeach</div></nav>
                <nav class="hidden space-y-6 lg:block" aria-label="Tài khoản biên tập viên"><div><p class="mb-2 px-3 font-label-sm text-label-sm font-semibold uppercase tracking-wide text-on-surface-variant">Hồ sơ</p><a href="{{ $profileRoute() }}" @class(['flex items-center gap-2.5 rounded-lg px-3 py-2.5 font-label-md text-label-md', 'bg-primary/10 font-semibold text-primary' => $tab === 'profile', 'text-on-surface-variant hover:bg-surface-container-low' => $tab !== 'profile'])><span class="material-symbols-outlined text-[20px]">person</span>Hồ sơ biên tập</a></div><div><p class="mb-2 px-3 font-label-sm text-label-sm font-semibold uppercase tracking-wide text-on-surface-variant">Tài khoản</p><div class="space-y-0.5">@foreach (['security' => ['Bảo mật', 'lock'], 'appearance' => ['Giao diện', 'palette']] as $key => [$label, $icon])<a href="{{ $profileRoute($key) }}" @class(['flex items-center gap-2.5 rounded-lg px-3 py-2.5 font-label-md text-label-md', 'bg-primary/10 font-semibold text-primary' => $tab === $key, 'text-on-surface-variant hover:bg-surface-container-low' => $tab !== $key])><span class="material-symbols-outlined text-[20px]">{{ $icon }}</span>{{ $label }}</a>@endforeach</div></div></nav>
            </aside>
            <div class="min-w-0 flex-1 space-y-6">
                <header class="space-y-1"><h2 class="font-headline-lg text-headline-lg-mobile text-on-surface md:text-headline-lg">{{ $title }}</h2><p class="font-body-md text-body-md text-on-surface-variant">{{ $description }}</p></header>
                @if (session('status'))<div role="alert" class="flex items-start gap-3 rounded-xl border border-primary/20 bg-primary/5 px-4 py-3"><span class="material-symbols-outlined mt-0.5 text-primary">check_circle</span><p class="font-body-md text-body-md">{{ session('status') }}</p></div>@endif
                @if ($errors->any())<div role="alert" class="rounded-xl border border-error/30 bg-error-container px-4 py-3 text-on-error-container"><ul class="list-disc space-y-1 pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

                @if ($tab === 'profile')
                    @if ($profileCompletion < 100)<section class="rounded-xl border border-outline-variant bg-surface p-4 md:p-5"><div class="mb-2 flex items-center justify-between gap-3"><p class="font-label-md text-label-md font-semibold text-on-surface">Hoàn thiện hồ sơ</p><span class="font-label-sm text-label-sm font-semibold text-primary">{{ $profileCompletion }}%</span></div><div class="h-2 overflow-hidden rounded-full bg-surface-container-high"><div class="h-full rounded-full bg-primary transition-all duration-500" style="width: {{ $profileCompletion }}%"></div></div><p class="mt-2 font-body-sm text-body-sm text-on-surface-variant">{{ filled($user->avatar_path) ? 'Bổ sung thông tin tài khoản để hoàn thiện hồ sơ.' : 'Tải ảnh đại diện để hoàn thiện hồ sơ biên tập.' }}</p></section>@endif
                    <section class="overflow-hidden rounded-xl border border-outline-variant bg-surface shadow-sm"><div class="border-b border-outline-variant bg-surface-container-lowest/60 px-5 py-4 md:px-6"><h3 class="font-title-md text-title-md">Thông tin tài khoản</h3><p class="mt-0.5 font-body-sm text-body-sm text-on-surface-variant">Ảnh đại diện và tên hiển thị của biên tập viên.</p></div><div class="space-y-6 p-5 md:p-6"><div class="flex flex-col gap-5 sm:flex-row sm:items-start">@include('auth::partials.avatar', ['user' => $user, 'size' => 'lg'])<div><p class="font-headline-sm text-headline-sm">{{ $user->name }}</p><p class="font-body-md text-body-md text-on-surface-variant">{{ $user->email }}</p><span class="mt-2 inline-flex rounded-full bg-primary/10 px-3 py-1 font-label-sm text-label-sm font-medium text-primary">Biên tập viên</span></div></div>
                    @can('editor_profile.avatar_update')<div class="rounded-lg border border-dashed border-outline-variant bg-surface-container-lowest/50 p-4"><form method="post" action="{{ route('editor.profile.avatar') }}" enctype="multipart/form-data" class="flex flex-col gap-3 sm:flex-row sm:items-end">@csrf @method('PUT')<div class="min-w-0 flex-1"><label for="avatar" class="font-label-sm text-label-sm font-medium text-on-surface-variant">Ảnh đại diện</label><p class="mb-2 font-body-sm text-body-sm text-on-surface-variant">JPG, PNG hoặc WebP — tối đa 2 MB</p><input id="avatar" name="avatar" type="file" required accept="image/jpeg,image/png,image/webp" class="block w-full text-body-sm file:mr-3 file:rounded-lg file:border-0 file:bg-primary file:px-4 file:py-2 file:font-label-md file:text-on-primary"></div><button class="rounded-lg bg-primary px-5 py-2.5 font-label-md font-semibold text-on-primary">Tải lên</button></form>@if (filled($user->getAttributes()['avatar_path'] ?? null))<form method="post" action="{{ route('editor.profile.avatar.destroy') }}" class="mt-3">@csrf @method('DELETE')<button class="font-label-sm text-on-surface-variant hover:text-error">Xóa ảnh hiện tại</button></form>@endif</div>@endcan
                    @can('editor_profile.update')<form method="post" action="{{ route('editor.profile.update') }}" class="border-t border-outline-variant pt-5">@csrf @method('PUT')<label for="name" class="font-label-sm text-label-sm font-medium text-on-surface-variant">Tên hiển thị</label><input id="name" name="name" required value="{{ old('name', $user->name) }}" class="{{ $inputClass }}"><div class="mt-4 flex justify-end"><button class="rounded-lg bg-primary px-5 py-2.5 font-label-md font-semibold text-on-primary">Lưu thay đổi</button></div></form>@endcan</div></section>
                @elseif ($tab === 'security')
                    @php
                        $googleAccount = $user->socialAccounts->firstWhere('provider', 'google');
                        $facebookAccount = $user->socialAccounts->firstWhere('provider', 'facebook');
                        $lastLoginMethod = $user->last_login_method?->value ?? $user->last_login_method;
                        $lastLoginLabel = ['email' => 'Email và mật khẩu', 'google' => 'Google', 'facebook' => 'Facebook'][$lastLoginMethod] ?? 'Chưa xác định';
                    @endphp
                    <section class="overflow-hidden rounded-xl border border-outline-variant bg-surface shadow-sm"><div class="border-b border-outline-variant bg-surface-container-lowest/60 px-5 py-4 md:px-6"><h3 class="font-title-md text-title-md">Phương thức đăng nhập</h3><p class="mt-0.5 font-body-sm text-body-sm text-on-surface-variant">Kiểm tra cách bạn vừa đăng nhập và các phương thức đang được liên kết với tài khoản.</p></div><div class="space-y-5 p-5 md:p-6"><div class="flex flex-col gap-2 rounded-xl border border-primary/20 bg-primary/5 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-label-sm text-label-sm text-on-surface-variant">Lần đăng nhập gần nhất</p><p class="mt-1 font-body-md font-semibold text-on-surface">{{ $lastLoginLabel }}</p></div>@if ($user->last_login_at)<p class="font-body-sm text-on-surface-variant">{{ $user->last_login_at->locale('vi')->isoFormat('HH:mm, DD/MM/YYYY') }}</p>@endif</div><div class="divide-y divide-outline-variant/60 rounded-xl border border-outline-variant">@foreach ([['name' => 'Email và mật khẩu', 'description' => $user->email, 'connected' => filled($user->password_set_at), 'icon' => 'mail'], ['name' => 'Google', 'description' => $googleAccount?->provider_email ?? 'Chưa liên kết với Google', 'connected' => $googleAccount !== null, 'icon' => 'language'], ['name' => 'Facebook', 'description' => $facebookAccount?->provider_email ?? 'Chưa liên kết với Facebook', 'connected' => $facebookAccount !== null, 'icon' => 'public']] as $method)<div class="flex items-center gap-3 p-4"><span class="material-symbols-outlined text-[22px] text-on-surface-variant">{{ $method['icon'] }}</span><div class="min-w-0 flex-1"><p class="font-body-md font-medium text-on-surface">{{ $method['name'] }}</p><p class="truncate font-body-sm text-on-surface-variant">{{ $method['description'] }}</p></div><span @class(['inline-flex shrink-0 items-center gap-1 rounded-full px-2.5 py-1 font-label-sm font-semibold', 'bg-primary/10 text-primary' => $method['connected'], 'bg-surface-container-high text-on-surface-variant' => ! $method['connected']])>@if ($method['connected'])<span class="material-symbols-outlined text-[16px]">check_circle</span>Đã liên kết @else Chưa liên kết @endif</span></div>@endforeach</div><p class="font-body-sm text-on-surface-variant">Nếu không dùng Google hoặc Facebook, bạn đăng nhập bằng email và mật khẩu. Tài khoản có thể hỗ trợ nhiều phương thức cùng lúc.</p></div></section>
                    @can('editor_profile.password_update')<section class="overflow-hidden rounded-xl border border-outline-variant bg-surface shadow-sm"><div class="border-b border-outline-variant bg-surface-container-lowest/60 px-5 py-4 md:px-6"><h3 class="font-title-md text-title-md">Đổi mật khẩu</h3><p class="mt-0.5 font-body-sm text-body-sm text-on-surface-variant">Sử dụng mật khẩu mạnh, tối thiểu 8 ký tự.</p></div><form method="post" action="{{ route('editor.profile.password') }}" class="space-y-4 p-5 md:p-6">@csrf @method('PUT')@foreach (['current_password' => ['Mật khẩu hiện tại', 'current-password'], 'password' => ['Mật khẩu mới', 'new-password'], 'password_confirmation' => ['Xác nhận mật khẩu mới', 'new-password']] as $field => [$label, $autocomplete])<div class="max-w-md"><label for="{{ $field }}" class="font-label-sm text-label-sm font-medium text-on-surface-variant">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" type="password" required autocomplete="{{ $autocomplete }}" placeholder="{{ $field === 'current_password' ? '••••••••' : ($field === 'password' ? 'Tối thiểu 8 ký tự' : 'Nhập lại mật khẩu mới') }}" class="{{ $inputClass }} @error($field) border-error @enderror">@error($field)<p class="mt-1 text-sm text-error">{{ $message }}</p>@enderror@if ($field === 'current_password')<p class="mt-1"><a href="{{ route('password.request') }}" class="font-label-sm text-primary hover:underline">Quên mật khẩu?</a></p>@endif</div>@endforeach<div class="flex justify-end border-t border-outline-variant pt-4"><button class="rounded-lg bg-primary px-5 py-2.5 font-label-md font-semibold text-on-primary">Cập nhật mật khẩu</button></div></form></section>@endcan
                    @can('editor_profile.two_factor_toggle')<section class="overflow-hidden rounded-xl border border-outline-variant bg-surface shadow-sm"><div class="border-b border-outline-variant bg-surface-container-lowest/60 px-5 py-4 md:px-6"><h3 class="flex items-center gap-2 font-title-md text-title-md"><span class="material-symbols-outlined text-primary">phonelink_lock</span>Xác thực hai bước (2FA)</h3><p class="mt-0.5 font-body-sm text-on-surface-variant">Tăng bảo mật bằng mã từ ứng dụng Authenticator. Bạn có thể bật hoặc tắt bất cứ lúc nào bằng mật khẩu hiện tại.</p></div><div class="p-5 md:p-6">@if ($user->hasTwoFactorEnabled())<span class="mb-5 inline-flex rounded-md bg-primary/10 px-2.5 py-1 font-label-sm font-semibold text-primary">Đã bật</span><form method="post" action="{{ route('editor.profile.2fa.disable') }}" class="max-w-md space-y-4">@csrf @method('DELETE')<div><label for="disable_2fa_password" class="font-label-sm text-on-surface-variant">Mật khẩu hiện tại để tắt 2FA</label><input id="disable_2fa_password" name="current_password" type="password" required autocomplete="current-password" placeholder="••••••••" class="{{ $inputClass }} @error('current_password') border-error @enderror">@error('current_password')<p class="mt-1 text-sm text-error">{{ $message }}</p>@enderror</div><button class="rounded-lg border border-error/40 bg-error-container px-5 py-2.5 font-label-md font-semibold text-on-error-container">Tắt xác thực hai bước</button></form>@else<a href="{{ route('editor.profile.2fa.setup') }}" class="inline-flex rounded-lg bg-primary px-5 py-2.5 font-label-md font-semibold text-on-primary">Bật 2FA</a>@endif</div></section>@endcan
                @else
                    <section class="overflow-hidden rounded-xl border border-outline-variant bg-surface shadow-sm" x-data="{ theme: 'system', init() { this.theme = window.MedlearnTheme?.getStoredTheme?.() ?? 'system' }, async setTheme(value) { this.theme = value; if (window.MedlearnTheme?.setTheme) this.theme = await window.MedlearnTheme.setTheme(value) } }" x-init="init()"><div class="border-b border-outline-variant bg-surface-container-lowest/60 px-5 py-4 md:px-6"><h3 class="font-title-md text-title-md">Chế độ giao diện</h3><p class="mt-0.5 font-body-sm text-body-sm text-on-surface-variant">Lưu theo tài khoản và đồng bộ khi đăng nhập.</p></div><div class="p-5 md:p-6"><div class="grid max-w-md grid-cols-3 overflow-hidden rounded-lg border border-outline-variant"><template x-for="option in [{ value: 'light', label: 'Sáng' }, { value: 'dark', label: 'Tối' }, { value: 'system', label: 'Hệ thống' }]" :key="option.value"><button type="button" @click="setTheme(option.value)" x-text="option.label" class="border-r border-outline-variant px-2 py-2.5 font-label-md font-bold last:border-r-0" :class="theme === option.value ? 'bg-primary-container text-on-primary-container' : 'bg-surface text-on-surface-variant'"></button></template></div></div></section>
                @endif
            </div>
        </div>
    </div>
</x-layouts.editor>
