<?php

declare(strict_types=1);

namespace Modules\QuestionBank\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Modules\QuestionBank\Models\Topic;

final class VietnameseTopicSeeder extends Seeder
{
    /**
     * @var list<string>
     */
    private array $topics = [
        'Nội khoa cơ bản',
        'Nội khoa lâm sàng',
        'Nội khoa tổng quan',
        'Nội tiết cơ bản',
        'Nội tiết lâm sàng',
        'Tim mạch cơ bản',
        'Tim mạch lâm sàng',
        'Tim mạch chẩn đoán',
        'Hô hấp cơ bản',
        'Hô hấp lâm sàng',
        'Hô hấp điều trị',
        'Tiêu hóa cơ bản',
        'Tiêu hóa lâm sàng',
        'Tiêu hóa chẩn đoán',
        'Thận học cơ bản',
        'Thận học lâm sàng',
        'Tiết niệu cơ bản',
        'Tiết niệu lâm sàng',
        'Thần kinh cơ bản',
        'Thần kinh lâm sàng',
        'Thần kinh chẩn đoán',
        'Ngoại khoa cơ bản',
        'Ngoại khoa lâm sàng',
        'Ngoại khoa thực hành',
        'Sản phụ khoa cơ bản',
        'Sản phụ khoa lâm sàng',
        'Sản phụ khoa thực hành',
        'Nhi khoa cơ bản',
        'Nhi khoa lâm sàng',
        'Nhi khoa tổng quan',
        'Da liễu cơ bản',
        'Da liễu lâm sàng',
        'Mắt cơ bản',
        'Mắt lâm sàng',
        'Tai mũi họng cơ bản',
        'Tai mũi họng lâm sàng',
        'Cơ xương khớp cơ bản',
        'Cơ xương khớp lâm sàng',
        'Chẩn đoán hình ảnh cơ bản',
        'Chẩn đoán hình ảnh lâm sàng',
        'Chẩn đoán hình ảnh thực hành',
        'Hồi sức cơ bản',
        'Hồi sức lâm sàng',
        'Cấp cứu cơ bản',
        'Cấp cứu lâm sàng',
        'Truyền nhiễm cơ bản',
        'Truyền nhiễm lâm sàng',
        'Huyết học cơ bản',
        'Huyết học lâm sàng',
        'Ung bướu cơ bản',
        'Ung bướu lâm sàng',
        'Dược lý cơ bản',
        'Dược lý lâm sàng',
        'Giải phẫu cơ bản',
        'Giải phẫu lâm sàng',
        'Sinh lý cơ bản',
        'Sinh lý lâm sàng',
        'Miễn dịch cơ bản',
        'Miễn dịch lâm sàng',
        'Vi sinh cơ bản',
        'Vi sinh lâm sàng',
        'Ký sinh trùng cơ bản',
        'Ký sinh trùng lâm sàng',
        'Giải phẫu bệnh cơ bản',
        'Giải phẫu bệnh lâm sàng',
        'Phục hồi chức năng cơ bản',
        'Phục hồi chức năng lâm sàng',
        'Gây mê hồi sức cơ bản',
        'Gây mê hồi sức lâm sàng',
        'Dinh dưỡng cơ bản',
        'Dinh dưỡng lâm sàng',
        'Y học gia đình cơ bản',
        'Y học gia đình lâm sàng',
        'Y học cộng đồng cơ bản',
        'Y học cộng đồng lâm sàng',
        'Y học dự phòng cơ bản',
        'Y học dự phòng lâm sàng',
        'Sức khỏe tâm thần cơ bản',
        'Sức khỏe tâm thần lâm sàng',
        'Tâm thần cơ bản',
        'Tâm thần lâm sàng',
        'Lão khoa cơ bản',
        'Lão khoa lâm sàng',
        'Nhiễm khuẩn cơ bản',
        'Nhiễm khuẩn lâm sàng',
        'Bệnh nhiệt đới cơ bản',
        'Bệnh nhiệt đới lâm sàng',
        'Da liễu thực hành',
        'Ngoại thần kinh cơ bản',
        'Ngoại thần kinh lâm sàng',
        'Ngoại lồng ngực cơ bản',
        'Ngoại lồng ngực lâm sàng',
        'Ngoại tiêu hóa cơ bản',
        'Ngoại tiêu hóa lâm sàng',
        'Ngoại tiết niệu cơ bản',
        'Ngoại tiết niệu lâm sàng',
        'Ngoại chấn thương cơ bản',
        'Ngoại chấn thương lâm sàng',
        'Sản khoa cơ bản',
        'Sản khoa lâm sàng',
        'Phụ khoa cơ bản',
        'Phụ khoa lâm sàng',
        'Sơ sinh cơ bản',
        'Sơ sinh lâm sàng',
        'Nhi tim mạch cơ bản',
        'Nhi tim mạch lâm sàng',
        'Nhi hô hấp cơ bản',
        'Nhi hô hấp lâm sàng',
        'Nhi tiêu hóa cơ bản',
        'Nhi tiêu hóa lâm sàng',
        'Nhi thần kinh cơ bản',
        'Nhi thần kinh lâm sàng',
        'Nhi nội tiết cơ bản',
        'Nhi nội tiết lâm sàng',
        'Nhi truyền nhiễm cơ bản',
        'Nhi truyền nhiễm lâm sàng',
        'Tim mạch can thiệp',
        'Can thiệp mạch vành',
        'Can thiệp tim mạch',
        'Siêu âm tim cơ bản',
        'Siêu âm tim lâm sàng',
        'Điện tâm đồ cơ bản',
        'Điện tâm đồ lâm sàng',
        'X quang cơ bản',
        'X quang lâm sàng',
        'CT scan cơ bản',
        'CT scan lâm sàng',
        'MRI cơ bản',
        'MRI lâm sàng',
        'Nội soi cơ bản',
        'Nội soi lâm sàng',
        'Xét nghiệm cơ bản',
        'Xét nghiệm lâm sàng',
        'Hóa sinh cơ bản',
        'Hóa sinh lâm sàng',
        'Huyết thanh học cơ bản',
        'Huyết thanh học lâm sàng',
        'Hô hấp can thiệp',
        'Tiêu hóa can thiệp',
        'Thận lọc máu cơ bản',
        'Thận lọc máu lâm sàng',
        'Cấp cứu chấn thương',
        'Cấp cứu nội khoa',
        'Cấp cứu ngoại khoa',
        'Chẩn đoán trước sinh',
        'Sàng lọc sơ sinh',
        'Hậu phẫu cơ bản',
        'Hậu phẫu lâm sàng',
        'Theo dõi bệnh nhân',
        'Chăm sóc tích cực',
        'Quản lý đau',
        'Kiểm soát nhiễm khuẩn',
        'An toàn người bệnh',
    ];

    public function run(): void
    {
        Topic::query()->delete();

        foreach (array_slice($this->topics, 0, 150) as $index => $name) {
            Topic::query()->create([
                'name' => $name,
                'slug' => Str::slug($name).'-'.($index + 1),
                'type' => 'specialty',
                'order' => $index,
                'parent_id' => null,
            ]);
        }
    }
}
